version: "3.10"

services:
  web:
    build: .
    container_name: fastapi-online-course
    command: uvicorn main:app --reload --host=0.0.0.0 --port=8000
    depends_on:
      fast:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  fast:
    image: postgres:latest
    container_name: fastapi-course-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
