name: FastAPI CD

on:
  workflow_run:
    workflows: ["FastAPI CI"]
    types:
      - completed

jobs:
  deploy_fastapi:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e 

            REPO_DIR="fastapi-task"

            if [ ! -d "$REPO_DIR" ]; then
              echo "Cloning repository into $REPO_DIR..."
              git clone https://github.com/theMirmakhmudov/FastAPI-Task-JWT.git $REPO_DIR
            else
              echo "Repository already exists, pulling the latest changes..."
              cd $REPO_DIR
              git pull origin master
              cd ..
            fi

            if [ ! -d "$REPO_DIR" ]; then
              echo "Error: The directory '$REPO_DIR' does not exist after cloning or pulling the repository."
              exit 1
            fi

            echo "Navigating into $REPO_DIR directory..."
            cd $REPO_DIR

            if [ ! -d "venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv venv
            fi

            source venv/bin/activate

            echo "Installing dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt
            
            echo "Restarting FastAPI service..."
            sudo systemctl restart fastapi-task.service

            echo "✅ Successfully deployed"